---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/LiorJanus/proxy-gitops